export const NbaTeams: string[] = [
  "Hawks",
  "Celtics",
  "Nets",
  "Hornets",
  "Bulls",
  "Cavaliers",
  "Mavericks",
  "Nuggets",
  "Pistons",
  "Warriors",
  "Rockets",
  "Pacers",
  "Clippers",
];

// Plus tard : 
// afficher Forward et non F
// Mettre ensemble C-F et F-C et si je mets forward affiché les F-C aussi etc. 
export const Positions: string[] = [
  "F-G",
  "C-F",
  "G-F",
  "C",
  "G",
  "F-C",
  "F"
]

export const Heights: string[] = [
 "5-8",
 "6-0",
 "6-1",
 "6-2",
 "6-3",
 "6-4",
 "6-5",
 "6-6",
 "6-7",
 "6-8",
 "6-9",
 "6-10",
 "6-11",
 "7-1",
 "7-0",
 "7-2",
 "7-3",
 "7-4",
]

export const Weights: number[] = []
for(let i = 159; i < 306; i++) {
  Weights.push(i);
}


export const CollegeTeams: string[]  = [
  "Mississippi State",
  "Nevada",
  "Rockingham Flames (Aus.)",
  "Clemson",
  "West Virginia",
  "South Carolina",
  "Besiktas",
  "Mount Saint Mary's",
  "Arkansas",
  "Real Madrid",
  "MHP Riesen",
  "Western Kentucky",
  "Cajasol Sevilla",
  "Murray State",
  "Auburn",
  "Lipscomb",
  "Oregon State",
  "Santa Clara",
  "Cairns",
  "Houston",
  "Oklahoma State",
  "IMG Academy (FL)",
  "Southern California",
  "Utah State",
  "Washington",
  "Kentucky",
  "Radford",
  "Providence",
  "Vanderbilt",
  "Illawarra",
  "Washington State",
  "Georgetown",
  "Guangzhou Loong Lions",
  "St. John's",
  "Overtime Elite",
  "Northern Iowa",
  "Ratiopharm Ulm",
  "Syracuse",
  "Nebraska",
  "New Zealand Breakers",
  "San Diego State",
  "Tennessee",
  "Louisiana State",
  "Davidson",
  "NBA Global Academy",
  "Loyola-Maryland",
  "Colorado State",
  "Oregon",
  "Louisana-Lafayette",
  "Wheeling Jesuit",
  "Alabama",
  "Rutgers",
  "California-Santa Barbara",
  "Notre Dame",
  "Colorado",
  "DePaul",
  "Texas-Austin",
  "Edgewater HS (FL)",
  "Arizona State",
  "Villanova",
  "Indiana-Purdue Fort Wayne",
  "Texas Tech",
  "Georgia Tech",
  "Indiana",
  "Braunschweig",
  "Serbia",
  "Bowling Green",
  "Texas A&M",
  "Australian Institute of Sport",
  "Michigan",
  "St. Vincent-St. Mary HS (OH)",
  "Adelaide",
  "Minas",
  "Purdue",
  "Georgia",
  "Xavier",
  "Alabama-Birmingham",
  "JL Bourg-en-Bresse",
  "Tennessee-Chattanooga",
  "California",
  "California State-Fullerton",
  "Nebraska-Lincoln",
  "Brose Bamberg",
  "Metropolitans 92",
  "TCU",
  "Kansas",
  "Gonzaga",
  "Louisiana Tech",
  "Perth",
  "Oklahoma",
  "Baskonia",
  "Fresno State",
  "Creighton",
  "Fenerbahce",
  "Memphis",
  "San Francisco",
  "Crvena zvezda",
  "Missouri",
  "Cedevita",
  "Drexel",
  "South Carolina Upstate",
  "Texas-San Antonio",
  "Stanford",
  "Southern Methodist",
  "Baylor",
  "Minnesota",
  "Northwestern",
  "Maccabi Tel Aviv",
  "Wisconsin-Milwaukee",
  "Arizona",
  "Pepperdine",
  "Princeton",
  "Virginia Tech",
  "Louisville",
  "Maryland",
  "Pittsburgh",
  "Lehigh",
  "Boston College",
  "New Mexico State",
  "Wyoming",
  "UCLA",
  "St. Mary's",
  "Wake Forest",
  "Rouen, France",
  "Wichita State",
  "Mega Basket",
  "Florida State",
  "Le Mans",
  "Duke",
  "North Carolina",
  "Florida",
  "Akron",
  "Ohio State",
  "Seton Hall",
  "Marquette",
  "Bayern Munich",
  "Buffalo",
  "Eastern Michigan",
  "Central Florida",
  "Oakland",
  "Connecticut",
  "Belmont",
  "Iowa",
  "Virginia Commonwealth",
  "Cholet",
  "Rhode Island",
  "NBA G League Ignite",
]

export const Countries: string[] = [
  'Turkey',
  'Nigeria',
  'Switzerland',
  'Italy',
  'New Zealand',
  'China',
  'Cameroon',
  'Saint Lucia',
  'Sweden',
  'USA',
  'United Kingdom',
  'Netherlands',
  'Brazil',
  'Austria',
  'Dominican Republic',
  'Australia',
  'Germany',
  'Serbia',
  'Canada',
  'Angola',
  'Portugal',
  'Finland',
  'South Sudan',
  'Lithuania',
  'Ukraine',
  'Spain',
  'Croatia',
  'Latvia',
  'Sudan',
  'Mali',
  'Greece',
  'Bahamas',
  'Georgia',
  'Belgium',
  'France',
  'DRC', // République Démocratique du Congo
  'Israel',
  'Senegal',
  'Poland',
  'Japan',
  'Bosnia and Herzegovina',
  'Jamaica'
];