spring.application.name=NbaList
# FreeSQL / MySQL connection - use the full JDBC URL
spring.datasource.url=jdbc:mysql://sql7.freesqldatabase.com:3306/sql7811248?useSSL=false&serverTimezone=UTC
spring.datasource.username=sql7811248
spring.datasource.password=tX9rxV4GaB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true